site_name: MLE101
site_url: https://melodymd.github.io/MLE101/

theme:
  name: material
  palette:
    - scheme: default
      primary: light green
      accent: teal
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Coding:
      - Overview: coding.md
  - ML Coding:
      - Overview: ml_coding.md
  - ML Q&A:
      - Overview: ml_qa.md
  - ML System Design:
      - Overview: ml_system_design.md
